/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LineChip: typeof import('./components/LineChip.vue')['default']
    NextTrain: typeof import('./components/NextTrain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StationSelector: typeof import('./components/StationSelector.vue')['default']
    TrainList: typeof import('./components/TrainList.vue')['default']
  }
}
